name: Config Files Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  config-files-deployment:
    runs-on: self-hosted
    steps:
      - name: List files in the repository before checkout
        run: |
          ls ${{ github.workspace }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List files in the repository after checkout
        run: |
          ls ${{ github.workspace }}
        
